[package]
name = "event_loop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
tokio = { version = "1.38.0", features = ["sync", "rt"] }
tracing = "0.1.40"
